# PyTorch Fundamentals

### How to import Pytorch:

In [61]:
import torch
torch.__version__

'2.7.1'

## Tensors

A **tensor** is a generalization of scalars, vectors, and matrices:

| Tensor Type | Description              | Example Shape |
|-------------|--------------------------|---------------|
| Scalar      | Single number            | `()`          |
| Vector      | 1D array of numbers      | `(n,)`        |
| Matrix      | 2D array of numbers      | `(m, n)`      |
| Tensor      | N-dimensional array      | `(d1, d2, ..., dn)` |

Tensors can be **1D, 2D, 3D, or higher-dimensional** arrays used to represent data in machine learning and deep learning.

<img src="imgs/scalar-vector-matrix-tensor.png" alt="Tensor visualization" width="600"/>

<img src="imgs/scalar-vector-matrix-tensor2.png" alt="Tensor visualization" width="600"/>

### Creating Tensors

In [62]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [63]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [64]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [65]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

## Random tensors

In PyTorch, you usually don’t manually create tensors.
Instead, models begin with random tensors that get updated as they learn from data.

> Start with random numbers → Look at data → Update numbers → Repeat

As a data scientist, you control:
- Initialization (how the model starts),
- Representation (how it processes data),
- Optimization (how it updates).

To create a random tensor in PyTorch, use:

In [66]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2384, 0.4453, 0.0868, 0.5010],
         [0.8534, 0.1092, 0.6713, 0.2108],
         [0.2463, 0.3501, 0.8430, 0.1664]]),
 torch.float32)