# Exercises for 00.ipynb

#### 0. Setup

In [54]:
import torch

if torch.cuda.is_available():
    device = "cuda"  # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps"   # Apple GPU
else:
    device = "cpu"   # Fallback

print(f"Using device: {device}")

Using device: mps


#### 1. Create a random tensor with shape `(7, 7)`.

In [55]:
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
         [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
         [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
         [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
         [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
         [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
         [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]]),
 torch.Size([7, 7]))

#### 2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [56]:
random_tensor2 = torch.rand(size=(1, 7))
print(random_tensor2, random_tensor2.shape)
random_tensor2_T = random_tensor2.T


matrix_mult = torch.matmul(random_tensor, random_tensor2_T)
matrix_mult, matrix_mult.shape

tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]]) torch.Size([1, 7])


(tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]),
 torch.Size([7, 1]))

#### 3. Set the random seed to 0 and do exercises 1 & 2 over again.

In [57]:
torch.manual_seed(0)

rand_tensor1 = torch.rand(size=(7, 7))
rand_tensor2 = torch.rand(size=(1, 7))
matrix_mult2 = torch.matmul(rand_tensor1, rand_tensor2.T)
print("Matrix multiplication result:\n", matrix_mult2, matrix_mult2.shape)


Matrix multiplication result:
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


#### 4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

In [58]:
seed = 1234
torch.manual_seed(seed)

if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)

#### 5. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [59]:
tensor1 = torch.rand(size=(2, 3))
tensor2 = torch.rand(size=(2, 3))

tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Tensor1 device:", tensor1.device)
print("Tensor2 device:", tensor2.device)

Tensor1 device: mps:0
Tensor2 device: mps:0


#### 6. Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors).

In [60]:
tensors_mult = torch.matmul(tensor1, tensor2.T)
print("Tensors multiplication result:\n", tensors_mult)

Tensors multiplication result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')


#### 7. Find the maximum and minimum values of the output of 6.

In [61]:
print(tensors_mult.min())
print(tensors_mult.argmin())

tensor(0.3647, device='mps:0')
tensor(0, device='mps:0')


#### 8. Find the maximum and minimum index values of the output of 6.

In [62]:
print(tensors_mult.max())
print(tensors_mult.argmax())

tensor(0.5617, device='mps:0')
tensor(3, device='mps:0')


#### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [64]:
torch.manual_seed(7)
torch.cuda.manual_seed(7)

new_tensor = torch.rand(size=(1, 1, 1, 10))
print(new_tensor, new_tensor.shape)

new_tensor_squeezed = new_tensor.squeeze()
print(new_tensor_squeezed, new_tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
