# Exercises for 00.ipynb

#### 0. Setup

In [4]:
import torch

if torch.cuda.is_available():
    device = "cuda"  # NVIDIA GPU
elif torch.backends.mps.is_available():
    device = "mps"   # Apple GPU
else:
    device = "cpu"   # Fallback

print(f"Using device: {device}")

Using device: cuda


#### 1. Create a random tensor with shape `(7, 7)`.

In [5]:
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.4527, 0.4326, 0.1542, 0.0476, 0.4514, 0.1090, 0.8557],
         [0.6559, 0.5342, 0.2628, 0.8133, 0.0328, 0.4470, 0.9976],
         [0.7571, 0.5287, 0.9761, 0.8503, 0.2904, 0.3653, 0.7061],
         [0.7018, 0.8475, 0.7127, 0.6767, 0.1754, 0.4153, 0.3370],
         [0.6882, 0.4610, 0.3742, 0.0441, 0.7644, 0.2064, 0.1995],
         [0.2188, 0.3040, 0.3238, 0.4975, 0.3518, 0.7127, 0.0925],
         [0.2338, 0.4277, 0.2564, 0.1543, 0.8000, 0.7889, 0.8338]]),
 torch.Size([7, 7]))

#### 2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
random_tensor2 = torch.rand(size=(1, 7))
print(random_tensor2, random_tensor2.shape)
random_tensor2_T = random_tensor2.T


matrix_mult = torch.matmul(random_tensor, random_tensor2_T)
matrix_mult, matrix_mult.shape

tensor([[0.8394, 0.2568, 0.4527, 0.9511, 0.2315, 0.7387, 0.1033]]) torch.Size([1, 7])


(tensor([[0.8797],
         [2.0211],
         [2.4319],
         [2.1552],
         [1.2574],
         [1.4990],
         [1.4231]]),
 torch.Size([7, 1]))

#### 3. Set the random seed to 0 and do exercises 1 & 2 over again.

In [7]:
torch.manual_seed(0)

rand_tensor1 = torch.rand(size=(7, 7))
rand_tensor2 = torch.rand(size=(1, 7))
matrix_mult2 = torch.matmul(rand_tensor1, rand_tensor2.T)
print("Matrix multiplication result:\n", matrix_mult2, matrix_mult2.shape)


Matrix multiplication result:
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


#### 4. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

In [8]:
seed = 1234
torch.manual_seed(seed)

if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)

#### 5. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed).

In [9]:
tensor1 = torch.rand(size=(2, 3))
tensor2 = torch.rand(size=(2, 3))

tensor1 = tensor1.to(device)
tensor2 = tensor2.to(device)

print("Tensor1 device:", tensor1.device)
print("Tensor2 device:", tensor2.device)

Tensor1 device: cuda:0
Tensor2 device: cuda:0


#### 6. Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors).

In [10]:
tensors_mult = torch.matmul(tensor1, tensor2.T)
print("Tensors multiplication result:\n", tensors_mult)

Tensors multiplication result:
 tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


#### 7. Find the maximum and minimum values of the output of 6.

In [11]:
print(tensors_mult.min())
print(tensors_mult.argmin())

tensor(0.3647, device='cuda:0')
tensor(0, device='cuda:0')


#### 8. Find the maximum and minimum index values of the output of 6.

In [12]:
print(tensors_mult.max())
print(tensors_mult.argmax())

tensor(0.5617, device='cuda:0')
tensor(3, device='cuda:0')


#### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [13]:
torch.manual_seed(7)
torch.cuda.manual_seed(7)

new_tensor = torch.rand(size=(1, 1, 1, 10))
print(new_tensor, new_tensor.shape)

new_tensor_squeezed = new_tensor.squeeze()
print(new_tensor_squeezed, new_tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
